const nodemailer = require('nodemailer');

let transporter = null;

function getTransporter() {
  if (transporter) return transporter;

  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT || '587');
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !user || !pass) return null;

  transporter = nodemailer.createTransport({
    host, port,
    secure: port === 465,
    auth: { user, pass },
  });
  return transporter;
}

async function sendStudentReport({ to, studentName, examName, courseName, totalMarks, maxMarks, percentage, questionResults, feedback, professorName }) {
  const t = getTransporter();
  if (!t) throw new Error('Email is not configured. Set SMTP_HOST, SMTP_USER, SMTP_PASS in .env');

  const questionRows = questionResults.map(q =>
    `<tr><td style="padding:8px;border:1px solid #ddd;">${q.questionNo}</td>` +
    `<td style="padding:8px;border:1px solid #ddd;">${q.awarded}/${q.max}</td>` +
    `<td style="padding:8px;border:1px solid #ddd;">${q.feedback || '-'}</td></tr>`
  ).join('');

  const html = `
    <div style="font-family:Inter,Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;">
      <div style="background:#001a3a;color:white;padding:20px 24px;border-radius:8px 8px 0 0;">
        <h2 style="margin:0;">Intelligrade — Exam Results</h2>
        <p style="margin:4px 0 0;opacity:0.8;">${courseName} — ${examName}</p>
      </div>
      <div style="border:1px solid #ddd;border-top:none;padding:24px;border-radius:0 0 8px 8px;">
        <p>Dear <strong>${studentName}</strong>,</p>
        <p>Your results for <strong>${examName}</strong> are ready:</p>
        <div style="background:#f0f7ff;padding:16px;border-radius:8px;margin:16px 0;text-align:center;">
          <div style="font-size:2rem;font-weight:800;color:#001a3a;">${totalMarks} / ${maxMarks}</div>
          <div style="color:#666;">${percentage}%</div>
        </div>
        <h3 style="margin-top:20px;">Question-wise Breakdown</h3>
        <table style="width:100%;border-collapse:collapse;margin:12px 0;">
          <thead><tr style="background:#f5f5f5;">
            <th style="padding:8px;border:1px solid #ddd;text-align:left;">Question</th>
            <th style="padding:8px;border:1px solid #ddd;text-align:left;">Marks</th>
            <th style="padding:8px;border:1px solid #ddd;text-align:left;">Feedback</th>
          </tr></thead>
          <tbody>${questionRows}</tbody>
        </table>
        ${feedback ? `<div style="background:#fffbe6;padding:12px;border-radius:6px;margin:16px 0;"><strong>Recommended Focus Areas:</strong><br>${feedback}</div>` : ''}
        <p style="color:#666;font-size:0.85rem;margin-top:24px;">This report was generated by Intelligrade. For questions, contact ${professorName || 'your professor'}.</p>
      </div>
    </div>`;

  await t.sendMail({
    from: process.env.SMTP_FROM || process.env.SMTP_USER,
    to,
    subject: `[${courseName}] ${examName} — Your Results`,
    html,
  });
}

async function isConfigured() {
  return !!(process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS);
}

module.exports = { sendStudentReport, isConfigured, getTransporter };
